name: Test Single Prediction

on:
  push:
    branches: [ main ]

jobs:
  test-single:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t car-inference-api ./

    - name: Run container
      run: docker run -d -p 4723:4723 --name car-api car-inference-api

    - name: Wait for API to be ready
      run: |
        for i in {1..10}; do
          curl -s http://localhost:4723/health && break || sleep 3
        done

    - name: Test single prediction
      run: python testing/ci.py predict
