name: Test 100 Randomized Single Predictions

on:
  workflow_run:
    workflows: [Build and Publish FastAPI Docker Image]
    types:
      - completed

jobs:
  test-random:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull published image
      run: |
        docker pull ghcr.io/ethanpisani/car-inference-api:latest
        docker run -d -p 4723:4723 --name car-api ghcr.io/ethanpisani/car-inference-api:latest

    - name: Wait for API to be ready
      run: |
        for i in {1..10}; do
          curl -s http://localhost:4723/health && break || sleep 3
        done

    - name: Test 100 randomized single POST requests
      run: python testing/ci.py random
